# ASP.NET Core (.NET Framework)

# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main
 
pool:
  vmImage: 'windows-latest'
 
variables:
  solution: '**/StoreApp/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
 
steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'P1'
    organization: '210215-usf-net'
    scannerMode: 'MSBuild'
    projectKey: '210215-USF-NET_Kevin_Murphy-P1'
    projectName: 'Kevin_Murphy-P1'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/StoreApp/*.sln'
 
# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'test'
#     projects: '**/StoreApp/*.sln'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    zipAfterPublish: true
    projects: '**/StoreApp/StoreMVC/*.csproj'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(87102de3-6040-4b65-953f-5976b2ac669e)'
    appType: 'webApp'
    WebAppName: 'PartsStore'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'